[pytest]
pythonpath = .
markers =
    unit: run unit tests enhetstester
    integration: run integration tests integrationstester
    slow: run slow tests
    performance: run performance tests prestandatest
    insertion: run performance tests on insertion sort
    merge: run performance tests on merge sort