[pytest]
pythonpath = .
markers =
    unit: run unit tests enhetstester
    integration: run integration tests integrationstester
    slow: run slow tests
    performance: run performance tests prestandatest